# dvc.yaml

# Top-level: just tell DVC which file is the params file
params:
  - params.yaml

stages:
  ingest:
    cmd: python src/ingest/ingest.py data/raw/sales.csv --out data/interim/ingested.csv
    deps:
      - src/ingest/ingest.py
      - data/raw/sales.csv
    outs:
      - data/interim/ingested.csv

  features:
    # Interpolate values from params.yaml via ${...}
    cmd: >
      python src/features/build_features.py
      --in data/interim/ingested.csv
      --out data/processed/features.csv
      --target ${train.target}
      --use-one-hot ${features.use_one_hot}
      --include-price ${features.include_price}
      --include-promo ${features.include_promo}
      --include-holiday ${features.include_holiday}
      --include-competitor-diff ${features.include_competitor_diff}
    deps:
      - src/features/build_features.py
      - data/interim/ingested.csv
      - params.yaml
    outs:
      - data/processed/features.csv
    # Stage-level keys that should trigger rebuild if changed
    params:
      - train.target
      - features.use_one_hot
      - features.include_price
      - features.include_promo
      - features.include_holiday
      - features.include_competitor_diff

  train:
    # Pass alpha/target in so the script uses your params
    cmd: >
      python src/models/train_baseline.py
      --in data/processed/features.csv
      --model models/baseline_linear.json
      --metrics models/metrics_baseline.json
      --alpha ${train.alpha}
      --target ${train.target}
    deps:
      - src/models/train_baseline.py
      - data/processed/features.csv
      - params.yaml
    outs:
      - models/baseline_linear.json
      - models/metrics_baseline.json
    # Stage-level params to watch
    params:
      - train.alpha
      - train.target
      - features.use_one_hot
      - features.include_price
      - features.include_promo
      - features.include_holiday
      - features.include_competitor_diff
    automl_pycaret:
    cmd: >
      python src/automl/pycaret_regression.py
      --in data/processed/features.csv
      --target ${train.target}
      --leaderboard reports/pycaret_leaderboard.csv
      --pred-sample reports/pycaret_predictions_sample.csv
      --model-dir models/pycaret_best
      --metrics reports/pycaret_metrics.json
      --experiment-name pycaret-regression
      --tracking-uri file:./mlruns
    deps:
      - src/automl/pycaret_regression.py
      - data/processed/features.csv
      - params.yaml
    outs:
      - reports/pycaret_leaderboard.csv
      - reports/pycaret_predictions_sample.csv
      - reports/pycaret_metrics.json
      - models/pycaret_best.pkl
    params:
      - train.target
